# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mpdye-g_AodHo4PuWeT5OJSX2Q-3ZN2J
"""

# n=10
# print(n*n)
# ### 1 - Crie um programa para efetuar a leitura de um número inteiro e apresentar o resultado do quadrado deste número.



# number=int(input("digite um numero"))
# quadrado= number * number
# print (quadrado)



# ### 2 -
# Crie duas variáveis para armazenar seu primeiro nome e sobrenome. Em seguida, concatene-as para formar seu nome completo e exiba o resultado.



# nome = "henrique"
# sobrenome = 'cyriaco'
# print (nome , sobrenome)


# ### 3 -
# Peça ao usuário para digitar dois números inteiros e armazene-os em variáveis. Realize a concatenação desses números como strings e exiba o resultado.



# n1 =  input ('digite um numero')
# n2 = input ("digite um numero")
# print ( print , n1+n2)


# ### 4 -
# Crie uma variável para armazenar a palavra "Python". Em seguida, adicione um número inteiro ao final da palavra usando a concatenação e exiba o resultado.


# palavra= "python"
# n1= int(input())
# print( palavra ,n1)



# format
# nome =  input ('digite aqui o seu nome')
# idade =  input ('digite aqui sua idade')
# meu_endereco = input ("digite seu endereco")
# cargo = input ( "digite aqui seu cargo")

#  print ('meu nome é,', nome ,'minha idade é,',idade, 'meu_endereco,', meu_endereco,' meu cargo é,',cargo)

# print(f'meu no3me e{nome},minha idade é{idade},meu_endereco é {meu_endereco},meu cargo é{cargo}')



# ### 5 -
# Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.

# frase = "ola como vai"
# palavra = input ('digite aqui palavra')
# print (frase,palavra)

# palavra = "bom dia"
# nome= input ('digite aqui seu nome -')
# print (palavra , nome)




# **6 -**

# **Crie três variáveis para armazenar a quantidade de horas, minutos e segundos. Concatene esses valores para formar uma mensagem de tempo no formato "hh:mm:ss".**

# hh = input ("digite a hora aqui " )
# mm = input("digite o minutos aqui " )
# ss = input ("digite o segundo aqui " )
# print (f'hh {hh}:mm {mm}:ss {ss} ' )




# **7 -
# Declare duas variáveis com números de telefone, incluindo um código de área e o número principal. Concatene esses valores para formar um número de telefone completo.**

# ddd = input ("digite o codigo de area ")
# telefone = input ("digite o seu telefone ")
# print (f'ddd {ddd}: telefone { telefone}' )

# **8 -
# Crie uma lista de ingredientes para uma receita. Use concatenação para formar uma única string que liste os ingredientes separados por vírgulas.**







# **9 -
# Peça ao usuário para digitar três adjetivos e armazene-os em variáveis. Em seguida, use essas palavras para criar uma frase concatenada que descreve algo interessante.**








# [Resolução dos exercícios atividade 3](https://www.notion.so/Resolu-o-dos-exerc-cios-atividade-3-04ad95281e544622b7d3d883da9b8112?pvs=21)









# condicionais
# ex




# numero = float (input("digite um (numero"))
# if numero  == 10:
#    print (f"0 numero e 10 ")
# else:
#   print (f' opa e {numero}')










# senha_gigitada  = input ( 'digite uma senha')

# senha = 123456
# if senha == senha_digitada:
#   print ( "acessar ")
# else:
#       print("nao pode acessar")




# and mais restrito

# senha_digitada  = input ( 'digite uma senha')
# nome=  input("digite seu nome")
# senha = "1234"
# if senha == senha_digitada and nome == "henrique":
#    print("acesse , vc digitou corretamente" )
# else:
#    print(f"nao pode acessar , porque voce digitou {senha } ou {nome} incorreto")






# or mais flexcivel pra entrada de senha ou nome menas restricao


# senha_digitada  = input ( 'digite uma senha')
# nome=  input("digite seu nome")
# senha = "1234"
# if senha == senha_digitada or nome == "henrique":
#    print("acesse , vc digitou corretamente" )
# else:
#    print(f"nao pode acessar , porque voce digitou {senha } ou {nome} incorreto")













# exercicio 1 aula 3

# idade =  int(input("Digite sua idade"))

# idade1 = 17
# idade2 = 20

# if idade1 >= idade2:
#    print ("a idade1 e maior")
# else:
#   print("a idade 2 é maior")


# idade  =  int(input("Digite sua idade"))

# if idade >= 18:
#    print("Pode entrar")
# else:
#     print("Não pode entrar")








# exer
# nota1 = float(input("Digite a nota 1 -  "))
# nota2 = float(input("Digite a nota 2 - "))
# nota3 = float(input("Digite a nota 3 - "))

# media = (nota1  + nota2 + nota3)/3

# if media >= 7:
#     print("passou")
#     print(media)
# elif media ==  6:
#     print("Recuperação")
#     print(media)
# else:
#     print("Repetiu")
#     print(media)